security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory

    access_control:
        # Autorise spécifiquement la route de signature du contrat
        - { path: ^/client/sign-finish, roles: PUBLIC_ACCESS }

        # Autorise la gestion globale du crédit
        - { path: ^/front/credit-gestion, roles: PUBLIC_ACCESS }
        
        # Tes autres règles
        - { path: ^/investisseur/marketplace, roles: PUBLIC_ACCESS }
        - { path: ^/frontOffice/credit, roles: PUBLIC_ACCESS }