<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402224611 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY `FK_2AF5A5CA76ED395`');
        $this->addSql('ALTER TABLE asset CHANGE symbol symbol VARCHAR(20) NOT NULL, CHANGE name name VARCHAR(100) NOT NULL, CHANGE current_price current_price DOUBLE PRECISION NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('DROP INDEX fk_userid ON asset');
        $this->addSql('CREATE INDEX IDX_2AF5A5CA76ED395 ON asset (user_id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT `FK_2AF5A5CA76ED395` FOREIGN KEY (user_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY `fk_block_credit_card`');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY `fk_block_transaction`');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY `fk_block_wallet_destination`');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY `fk_block_wallet_source`');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY `fk_block_credit_card`');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY `fk_block_transaction`');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY `fk_block_wallet_destination`');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY `fk_block_wallet_source`');
        $this->addSql('ALTER TABLE blockchain CHANGE id_transaction id_transaction INT DEFAULT NULL, CHANGE type type VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT FK_2A493AAA6A25C826 FOREIGN KEY (id_transaction) REFERENCES transaction (id_transaction)');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT FK_2A493AAAEF2AE037 FOREIGN KEY (wallet_source) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT FK_2A493AAA4B2BC209 FOREIGN KEY (wallet_destination) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT FK_2A493AAA9D3484D1 FOREIGN KEY (id_card) REFERENCES credit_card (id_card)');
        $this->addSql('DROP INDEX fk_block_transaction ON blockchain');
        $this->addSql('CREATE INDEX IDX_2A493AAA6A25C826 ON blockchain (id_transaction)');
        $this->addSql('DROP INDEX fk_block_wallet_source ON blockchain');
        $this->addSql('CREATE INDEX IDX_2A493AAAEF2AE037 ON blockchain (wallet_source)');
        $this->addSql('DROP INDEX fk_block_wallet_destination ON blockchain');
        $this->addSql('CREATE INDEX IDX_2A493AAA4B2BC209 ON blockchain (wallet_destination)');
        $this->addSql('DROP INDEX fk_block_credit_card ON blockchain');
        $this->addSql('CREATE INDEX IDX_2A493AAA9D3484D1 ON blockchain (id_card)');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT `fk_block_credit_card` FOREIGN KEY (id_card) REFERENCES credit_card (id_card) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT `fk_block_transaction` FOREIGN KEY (id_transaction) REFERENCES transaction (id_transaction) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT `fk_block_wallet_destination` FOREIGN KEY (wallet_destination) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT `fk_block_wallet_source` FOREIGN KEY (wallet_source) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE certificats DROP FOREIGN KEY `fk_idParticipation`');
        $this->addSql('ALTER TABLE certificats MODIFY idCertificat INT NOT NULL');
        $this->addSql('ALTER TABLE certificats CHANGE idParticipation idParticipation INT DEFAULT NULL, CHANGE mention mention VARCHAR(255) DEFAULT NULL, CHANGE idCertificat id_certificat INT AUTO_INCREMENT NOT NULL, CHANGE dateEmission date_emission DATE NOT NULL, CHANGE urlFichier url_fichier VARCHAR(255) DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id_certificat)');
        $this->addSql('DROP INDEX fk_certificat_participation ON certificats');
        $this->addSql('CREATE INDEX IDX_D5486F1B61B1BE61 ON certificats (idParticipation)');
        $this->addSql('ALTER TABLE certificats ADD CONSTRAINT `fk_idParticipation` FOREIGN KEY (idParticipation) REFERENCES participations (idParticipation)');
        $this->addSql('ALTER TABLE conversion DROP FOREIGN KEY `fk_conversion_currency_from`');
        $this->addSql('ALTER TABLE conversion DROP FOREIGN KEY `fk_conversion_currency_to`');
        $this->addSql('ALTER TABLE conversion DROP FOREIGN KEY `fk_conversion_currency_from`');
        $this->addSql('ALTER TABLE conversion DROP FOREIGN KEY `fk_conversion_currency_to`');
        $this->addSql('ALTER TABLE conversion DROP amount_to, CHANGE currency_from currency_from INT DEFAULT NULL, CHANGE currency_to currency_to INT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT FK_BD91274433ADE204 FOREIGN KEY (currency_from) REFERENCES currency (id_currency)');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT FK_BD912744509A34E2 FOREIGN KEY (currency_to) REFERENCES currency (id_currency)');
        $this->addSql('DROP INDEX fk_conversion_currency_from ON conversion');
        $this->addSql('CREATE INDEX IDX_BD91274433ADE204 ON conversion (currency_from)');
        $this->addSql('DROP INDEX fk_conversion_currency_to ON conversion');
        $this->addSql('CREATE INDEX IDX_BD912744509A34E2 ON conversion (currency_to)');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT `fk_conversion_currency_from` FOREIGN KEY (currency_from) REFERENCES currency (id_currency) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT `fk_conversion_currency_to` FOREIGN KEY (currency_to) REFERENCES currency (id_currency) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY `fk_credit_borrower`');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY `fk_credit_investisseur`');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY `fk_credit_projet`');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY `fk_credit_borrower`');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY `fk_credit_investisseur`');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY `fk_credit_projet`');
        $this->addSql('ALTER TABLE credit CHANGE project_id project_id INT DEFAULT NULL, CHANGE borrower_id borrower_id INT DEFAULT NULL, CHANGE montant montant NUMERIC(18, 2) NOT NULL, CHANGE devise devise VARCHAR(255) NOT NULL, CHANGE taux taux NUMERIC(9, 6) NOT NULL, CHANGE duree duree INT NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE contrat_id contrat_id VARCHAR(255) DEFAULT NULL, CHANGE date_demande date_demande DATETIME NOT NULL');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE166D1F9C FOREIGN KEY (project_id) REFERENCES projet (id_projet)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE11CE312B FOREIGN KEY (borrower_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFEA8F9CCCA FOREIGN KEY (investisseur_id) REFERENCES utilisateur (id_user)');
        $this->addSql('DROP INDEX fk_credit_projet ON credit');
        $this->addSql('CREATE INDEX IDX_1CC16EFE166D1F9C ON credit (project_id)');
        $this->addSql('DROP INDEX fk_credit_borrower ON credit');
        $this->addSql('CREATE INDEX IDX_1CC16EFE11CE312B ON credit (borrower_id)');
        $this->addSql('DROP INDEX fk_credit_investisseur ON credit');
        $this->addSql('CREATE INDEX IDX_1CC16EFEA8F9CCCA ON credit (investisseur_id)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT `fk_credit_borrower` FOREIGN KEY (borrower_id) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT `fk_credit_investisseur` FOREIGN KEY (investisseur_id) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT `fk_credit_projet` FOREIGN KEY (project_id) REFERENCES projet (id_projet) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE credit_card DROP FOREIGN KEY `fk_creditcard_user`');
        $this->addSql('ALTER TABLE credit_card DROP FOREIGN KEY `fk_creditcard_user`');
        $this->addSql('ALTER TABLE credit_card CHANGE id_user id_user INT DEFAULT NULL, CHANGE card_holder_name card_holder_name VARCHAR(255) NOT NULL, CHANGE last_4_digits last_4_digits VARCHAR(255) NOT NULL, CHANGE stripe_customer_id stripe_customer_id VARCHAR(255) DEFAULT NULL, CHANGE stripe_payment_method_id stripe_payment_method_id VARCHAR(255) DEFAULT NULL, CHANGE date_ajout date_ajout DATETIME DEFAULT NULL, CHANGE statut statut VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE credit_card ADD CONSTRAINT FK_11D627EE6B3CA4B FOREIGN KEY (id_user) REFERENCES utilisateur (id_user)');
        $this->addSql('DROP INDEX fk_creditcard_user ON credit_card');
        $this->addSql('CREATE INDEX IDX_11D627EE6B3CA4B ON credit_card (id_user)');
        $this->addSql('ALTER TABLE credit_card ADD CONSTRAINT `fk_creditcard_user` FOREIGN KEY (id_user) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE currency CHANGE code code VARCHAR(255) NOT NULL, CHANGE nom nom VARCHAR(255) NOT NULL, CHANGE type_currency type_currency VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE formations DROP FOREIGN KEY `fk_userIdFormation`');
        $this->addSql('ALTER TABLE formations CHANGE description description LONGTEXT DEFAULT NULL, CHANGE domaine domaine VARCHAR(255) DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL');
        $this->addSql('DROP INDEX fk_useridformation ON formations');
        $this->addSql('CREATE INDEX IDX_40902137A76ED395 ON formations (user_id)');
        $this->addSql('ALTER TABLE formations ADD CONSTRAINT `fk_userIdFormation` FOREIGN KEY (user_id) REFERENCES utilisateur (id_user)');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages');
        $this->addSql('ALTER TABLE messenger_messages CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE queue_name queue_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE negociation DROP FOREIGN KEY `fk_negociation_credit`');
        $this->addSql('ALTER TABLE negociation DROP FOREIGN KEY `fk_negociation_investor`');
        $this->addSql('ALTER TABLE negociation DROP FOREIGN KEY `fk_negociation_credit`');
        $this->addSql('ALTER TABLE negociation DROP FOREIGN KEY `fk_negociation_investor`');
        $this->addSql('ALTER TABLE negociation CHANGE credit_id credit_id INT DEFAULT NULL, CHANGE investor_id investor_id INT DEFAULT NULL, CHANGE montant montant NUMERIC(18, 2) NOT NULL, CHANGE taux_propose taux_propose NUMERIC(9, 6) NOT NULL, CHANGE status status VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE negociation ADD CONSTRAINT FK_B5E137D8CE062FF9 FOREIGN KEY (credit_id) REFERENCES credit (id_credit)');
        $this->addSql('ALTER TABLE negociation ADD CONSTRAINT FK_B5E137D89AE528DA FOREIGN KEY (investor_id) REFERENCES utilisateur (id_user)');
        $this->addSql('DROP INDEX fk_negociation_credit ON negociation');
        $this->addSql('CREATE INDEX IDX_B5E137D8CE062FF9 ON negociation (credit_id)');
        $this->addSql('DROP INDEX fk_negociation_investor ON negociation');
        $this->addSql('CREATE INDEX IDX_B5E137D89AE528DA ON negociation (investor_id)');
        $this->addSql('ALTER TABLE negociation ADD CONSTRAINT `fk_negociation_credit` FOREIGN KEY (credit_id) REFERENCES credit (id_credit) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE negociation ADD CONSTRAINT `fk_negociation_investor` FOREIGN KEY (investor_id) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification CHANGE type_notification type_notification VARCHAR(255) NOT NULL, CHANGE message message LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE is_read is_read TINYINT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY `fk_order_item_order`');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY `fk_order_item_product`');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY `fk_order_item_order`');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY `fk_order_item_product`');
        $this->addSql('ALTER TABLE order_item CHANGE product_id product_id INT DEFAULT NULL, CHANGE order_id order_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F094584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F098D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('DROP INDEX fk_order_item_product ON order_item');
        $this->addSql('CREATE INDEX IDX_52EA1F094584665A ON order_item (product_id)');
        $this->addSql('DROP INDEX fk_order_item_order ON order_item');
        $this->addSql('CREATE INDEX IDX_52EA1F098D9F6D38 ON order_item (order_id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT `fk_order_item_order` FOREIGN KEY (order_id) REFERENCES orders (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT `fk_order_item_product` FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY `fk_userIdInOrders`');
        $this->addSql('ALTER TABLE orders CHANGE order_date order_date DATETIME NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE shipping_address shipping_address LONGTEXT NOT NULL');
        $this->addSql('DROP INDEX fk_useridinorders ON orders');
        $this->addSql('CREATE INDEX IDX_E52FFDEEA76ED395 ON orders (user_id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT `fk_userIdInOrders` FOREIGN KEY (user_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE participations DROP FOREIGN KEY `fk_userIdP`');
        $this->addSql('ALTER TABLE participations CHANGE idFormation idFormation INT DEFAULT NULL, CHANGE dateInscription dateInscription DATETIME DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL, CHANGE presence presence TINYINT DEFAULT NULL, CHANGE note note DOUBLE PRECISION DEFAULT NULL, CHANGE idUtilisateur idUtilisateur INT DEFAULT NULL');
        $this->addSql('ALTER TABLE participations ADD CONSTRAINT FK_FDC6C6E8BCAA0AE9 FOREIGN KEY (idFormation) REFERENCES formations (idFormation)');
        $this->addSql('DROP INDEX fk_participation_formation ON participations');
        $this->addSql('CREATE INDEX IDX_FDC6C6E8BCAA0AE9 ON participations (idFormation)');
        $this->addSql('DROP INDEX fk_useridp ON participations');
        $this->addSql('CREATE INDEX IDX_FDC6C6E85D419CCB ON participations (idUtilisateur)');
        $this->addSql('ALTER TABLE participations ADD CONSTRAINT `fk_userIdP` FOREIGN KEY (idUtilisateur) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY `fk_product_user`');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY `fk_product_user`');
        $this->addSql('ALTER TABLE product CHANGE description description LONGTEXT DEFAULT NULL, CHANGE price price DOUBLE PRECISION NOT NULL, CHANGE discount_price discount_price DOUBLE PRECISION DEFAULT NULL, CHANGE brand brand VARCHAR(255) DEFAULT NULL, CHANGE avg_rating avg_rating DOUBLE PRECISION DEFAULT NULL, CHANGE image_url image_url LONGTEXT DEFAULT NULL, CHANGE stock stock INT DEFAULT NULL, CHANGE category category VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADA76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (id_user)');
        $this->addSql('DROP INDEX fk_product_user ON product');
        $this->addSql('CREATE INDEX IDX_D34A04ADA76ED395 ON product (user_id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT `fk_product_user` FOREIGN KEY (user_id) REFERENCES utilisateur (id_user) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY `fk_project_owner`');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY `fk_project_owner`');
        $this->addSql('ALTER TABLE projet CHANGE owner_id owner_id INT DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE image_url image_url LONGTEXT DEFAULT NULL, CHANGE secteur secteur VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA97E3C61F9 FOREIGN KEY (owner_id) REFERENCES utilisateur (id_user)');
        $this->addSql('DROP INDEX fk_project_owner ON projet');
        $this->addSql('CREATE INDEX IDX_50159CA97E3C61F9 ON projet (owner_id)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT `fk_project_owner` FOREIGN KEY (owner_id) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX fk_trade_user ON trade');
        $this->addSql('DROP INDEX fk_assetID ON trade');
        $this->addSql('ALTER TABLE trade CHANGE trade_type trade_type VARCHAR(255) NOT NULL, CHANGE order_mode order_mode VARCHAR(255) NOT NULL, CHANGE status status VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_card`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_currency`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_transaction_conversion`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_wallet_destination`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_wallet_source`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_card`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_currency`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_transaction_conversion`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_wallet_destination`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_wallet_source`');
        $this->addSql('ALTER TABLE transaction CHANGE id_wallet_destination id_wallet_destination INT DEFAULT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL, CHANGE date_transaction date_transaction DATETIME DEFAULT NULL, CHANGE id_currency id_currency INT DEFAULT NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D151023152 FOREIGN KEY (id_wallet_source) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1C80970A6 FOREIGN KEY (id_wallet_destination) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D19D3484D1 FOREIGN KEY (id_card) REFERENCES credit_card (id_card)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1398D64AA FOREIGN KEY (id_currency) REFERENCES currency (id_currency)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1181BA793 FOREIGN KEY (id_conversion) REFERENCES conversion (id_conversion)');
        $this->addSql('DROP INDEX fk_wallet_source ON transaction');
        $this->addSql('CREATE INDEX IDX_723705D151023152 ON transaction (id_wallet_source)');
        $this->addSql('DROP INDEX fk_wallet_destination ON transaction');
        $this->addSql('CREATE INDEX IDX_723705D1C80970A6 ON transaction (id_wallet_destination)');
        $this->addSql('DROP INDEX fk_card ON transaction');
        $this->addSql('CREATE INDEX IDX_723705D19D3484D1 ON transaction (id_card)');
        $this->addSql('DROP INDEX fk_currency ON transaction');
        $this->addSql('CREATE INDEX IDX_723705D1398D64AA ON transaction (id_currency)');
        $this->addSql('DROP INDEX fk_transaction_conversion ON transaction');
        $this->addSql('CREATE INDEX IDX_723705D1181BA793 ON transaction (id_conversion)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_card` FOREIGN KEY (id_card) REFERENCES credit_card (id_card) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_currency` FOREIGN KEY (id_currency) REFERENCES currency (id_currency) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_transaction_conversion` FOREIGN KEY (id_conversion) REFERENCES conversion (id_conversion) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_wallet_destination` FOREIGN KEY (id_wallet_destination) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_wallet_source` FOREIGN KEY (id_wallet_source) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur CHANGE role role VARCHAR(255) NOT NULL, CHANGE date_de_creation date_de_creation DATETIME NOT NULL, CHANGE date_derniere_connexion date_derniere_connexion DATETIME NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE wallet DROP FOREIGN KEY `fk_wallet_user`');
        $this->addSql('ALTER TABLE wallet CHANGE id_user id_user INT DEFAULT NULL, CHANGE rib rib VARCHAR(255) NOT NULL, CHANGE type_wallet type_wallet VARCHAR(255) DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL, CHANGE date_creation date_creation DATETIME NOT NULL, CHANGE date_derniere_modification date_derniere_modification DATETIME NOT NULL');
        $this->addSql('DROP INDEX id_user ON wallet');
        $this->addSql('CREATE INDEX IDX_7C68921F6B3CA4B ON wallet (id_user)');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT `fk_wallet_user` FOREIGN KEY (id_user) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE wallet_currency DROP FOREIGN KEY `fk_wallet`');
        $this->addSql('ALTER TABLE wallet_currency DROP FOREIGN KEY `fk_wc_currency`');
        $this->addSql('ALTER TABLE wallet_currency DROP FOREIGN KEY `fk_wallet`');
        $this->addSql('ALTER TABLE wallet_currency DROP FOREIGN KEY `fk_wc_currency`');
        $this->addSql('ALTER TABLE wallet_currency CHANGE id_wallet id_wallet INT DEFAULT NULL, CHANGE id_currency id_currency INT DEFAULT NULL, CHANGE solde solde DOUBLE PRECISION DEFAULT NULL, CHANGE nom_currency nom_currency VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE wallet_currency ADD CONSTRAINT FK_9DF33C4B5A5F27F2 FOREIGN KEY (id_wallet) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE wallet_currency ADD CONSTRAINT FK_9DF33C4B398D64AA FOREIGN KEY (id_currency) REFERENCES currency (id_currency)');
        $this->addSql('DROP INDEX fk_wallet ON wallet_currency');
        $this->addSql('CREATE INDEX IDX_9DF33C4B5A5F27F2 ON wallet_currency (id_wallet)');
        $this->addSql('DROP INDEX fk_wc_currency ON wallet_currency');
        $this->addSql('CREATE INDEX IDX_9DF33C4B398D64AA ON wallet_currency (id_currency)');
        $this->addSql('ALTER TABLE wallet_currency ADD CONSTRAINT `fk_wallet` FOREIGN KEY (id_wallet) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wallet_currency ADD CONSTRAINT `fk_wc_currency` FOREIGN KEY (id_currency) REFERENCES currency (id_currency) ON UPDATE CASCADE ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5CA76ED395');
        $this->addSql('ALTER TABLE asset CHANGE symbol symbol VARCHAR(255) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE current_price current_price NUMERIC(18, 8) NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_2af5a5ca76ed395 ON asset');
        $this->addSql('CREATE INDEX fk_userId ON asset (user_id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CA76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY FK_2A493AAA6A25C826');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY FK_2A493AAAEF2AE037');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY FK_2A493AAA4B2BC209');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY FK_2A493AAA9D3484D1');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY FK_2A493AAA6A25C826');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY FK_2A493AAAEF2AE037');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY FK_2A493AAA4B2BC209');
        $this->addSql('ALTER TABLE blockchain DROP FOREIGN KEY FK_2A493AAA9D3484D1');
        $this->addSql('ALTER TABLE blockchain CHANGE type type VARCHAR(50) NOT NULL, CHANGE id_transaction id_transaction INT NOT NULL');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT `fk_block_credit_card` FOREIGN KEY (id_card) REFERENCES credit_card (id_card) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT `fk_block_transaction` FOREIGN KEY (id_transaction) REFERENCES transaction (id_transaction) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT `fk_block_wallet_destination` FOREIGN KEY (wallet_destination) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT `fk_block_wallet_source` FOREIGN KEY (wallet_source) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_2a493aaaef2ae037 ON blockchain');
        $this->addSql('CREATE INDEX fk_block_wallet_source ON blockchain (wallet_source)');
        $this->addSql('DROP INDEX idx_2a493aaa4b2bc209 ON blockchain');
        $this->addSql('CREATE INDEX fk_block_wallet_destination ON blockchain (wallet_destination)');
        $this->addSql('DROP INDEX idx_2a493aaa9d3484d1 ON blockchain');
        $this->addSql('CREATE INDEX fk_block_credit_card ON blockchain (id_card)');
        $this->addSql('DROP INDEX idx_2a493aaa6a25c826 ON blockchain');
        $this->addSql('CREATE INDEX fk_block_transaction ON blockchain (id_transaction)');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT FK_2A493AAA6A25C826 FOREIGN KEY (id_transaction) REFERENCES transaction (id_transaction)');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT FK_2A493AAAEF2AE037 FOREIGN KEY (wallet_source) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT FK_2A493AAA4B2BC209 FOREIGN KEY (wallet_destination) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE blockchain ADD CONSTRAINT FK_2A493AAA9D3484D1 FOREIGN KEY (id_card) REFERENCES credit_card (id_card)');
        $this->addSql('ALTER TABLE certificats DROP FOREIGN KEY FK_D5486F1B61B1BE61');
        $this->addSql('ALTER TABLE certificats MODIFY id_certificat INT NOT NULL');
        $this->addSql('ALTER TABLE certificats CHANGE mention mention ENUM(\'VALIDE\', \'EXCELLENT\') DEFAULT \'VALIDE\', CHANGE idParticipation idParticipation INT NOT NULL, CHANGE id_certificat idCertificat INT AUTO_INCREMENT NOT NULL, CHANGE date_emission dateEmission DATE NOT NULL, CHANGE url_fichier urlFichier VARCHAR(255) DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idCertificat)');
        $this->addSql('DROP INDEX idx_d5486f1b61b1be61 ON certificats');
        $this->addSql('CREATE INDEX fk_certificat_participation ON certificats (idParticipation)');
        $this->addSql('ALTER TABLE certificats ADD CONSTRAINT FK_D5486F1B61B1BE61 FOREIGN KEY (idParticipation) REFERENCES participations (idParticipation)');
        $this->addSql('ALTER TABLE conversion DROP FOREIGN KEY FK_BD91274433ADE204');
        $this->addSql('ALTER TABLE conversion DROP FOREIGN KEY FK_BD912744509A34E2');
        $this->addSql('ALTER TABLE conversion DROP FOREIGN KEY FK_BD91274433ADE204');
        $this->addSql('ALTER TABLE conversion DROP FOREIGN KEY FK_BD912744509A34E2');
        $this->addSql('ALTER TABLE conversion ADD amount_to NUMERIC(18, 8) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE currency_from currency_from INT NOT NULL, CHANGE currency_to currency_to INT NOT NULL');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT `fk_conversion_currency_from` FOREIGN KEY (currency_from) REFERENCES currency (id_currency) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT `fk_conversion_currency_to` FOREIGN KEY (currency_to) REFERENCES currency (id_currency) ON UPDATE CASCADE');
        $this->addSql('DROP INDEX idx_bd91274433ade204 ON conversion');
        $this->addSql('CREATE INDEX fk_conversion_currency_from ON conversion (currency_from)');
        $this->addSql('DROP INDEX idx_bd912744509a34e2 ON conversion');
        $this->addSql('CREATE INDEX fk_conversion_currency_to ON conversion (currency_to)');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT FK_BD91274433ADE204 FOREIGN KEY (currency_from) REFERENCES currency (id_currency)');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT FK_BD912744509A34E2 FOREIGN KEY (currency_to) REFERENCES currency (id_currency)');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY FK_1CC16EFE166D1F9C');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY FK_1CC16EFE11CE312B');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY FK_1CC16EFEA8F9CCCA');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY FK_1CC16EFE166D1F9C');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY FK_1CC16EFE11CE312B');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY FK_1CC16EFEA8F9CCCA');
        $this->addSql('ALTER TABLE credit CHANGE montant montant DOUBLE PRECISION NOT NULL, CHANGE devise devise VARCHAR(8) DEFAULT \'EUR\' NOT NULL, CHANGE taux taux DOUBLE PRECISION NOT NULL, CHANGE duree duree INT UNSIGNED NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE status status ENUM(\'OPEN\', \'APPROVED\', \'REJECTED\', \'CLOSED\') DEFAULT \'OPEN\' NOT NULL, CHANGE contrat_id contrat_id VARCHAR(36) DEFAULT NULL, CHANGE date_demande date_demande DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE project_id project_id INT NOT NULL, CHANGE borrower_id borrower_id INT NOT NULL');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT `fk_credit_borrower` FOREIGN KEY (borrower_id) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT `fk_credit_investisseur` FOREIGN KEY (investisseur_id) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT `fk_credit_projet` FOREIGN KEY (project_id) REFERENCES projet (id_projet) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_1cc16efea8f9ccca ON credit');
        $this->addSql('CREATE INDEX fk_credit_investisseur ON credit (investisseur_id)');
        $this->addSql('DROP INDEX idx_1cc16efe166d1f9c ON credit');
        $this->addSql('CREATE INDEX fk_credit_projet ON credit (project_id)');
        $this->addSql('DROP INDEX idx_1cc16efe11ce312b ON credit');
        $this->addSql('CREATE INDEX fk_credit_borrower ON credit (borrower_id)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE166D1F9C FOREIGN KEY (project_id) REFERENCES projet (id_projet)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE11CE312B FOREIGN KEY (borrower_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFEA8F9CCCA FOREIGN KEY (investisseur_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE credit_card DROP FOREIGN KEY FK_11D627EE6B3CA4B');
        $this->addSql('ALTER TABLE credit_card DROP FOREIGN KEY FK_11D627EE6B3CA4B');
        $this->addSql('ALTER TABLE credit_card CHANGE card_holder_name card_holder_name VARCHAR(100) NOT NULL, CHANGE last_4_digits last_4_digits CHAR(4) NOT NULL, CHANGE stripe_customer_id stripe_customer_id VARCHAR(100) DEFAULT NULL, CHANGE stripe_payment_method_id stripe_payment_method_id VARCHAR(100) DEFAULT NULL, CHANGE date_ajout date_ajout DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE statut statut ENUM(\'ACTIVE\', \'EXPIRED\', \'DELETED\') DEFAULT \'ACTIVE\' NOT NULL, CHANGE id_user id_user INT NOT NULL');
        $this->addSql('ALTER TABLE credit_card ADD CONSTRAINT `fk_creditcard_user` FOREIGN KEY (id_user) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_11d627ee6b3ca4b ON credit_card');
        $this->addSql('CREATE INDEX fk_creditcard_user ON credit_card (id_user)');
        $this->addSql('ALTER TABLE credit_card ADD CONSTRAINT FK_11D627EE6B3CA4B FOREIGN KEY (id_user) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE currency CHANGE code code VARCHAR(10) NOT NULL, CHANGE nom nom VARCHAR(50) NOT NULL, CHANGE type_currency type_currency ENUM(\'fiat\', \'crypto\') NOT NULL');
        $this->addSql('ALTER TABLE formations DROP FOREIGN KEY FK_40902137A76ED395');
        $this->addSql('ALTER TABLE formations CHANGE description description TEXT DEFAULT NULL, CHANGE domaine domaine VARCHAR(100) DEFAULT NULL, CHANGE statut statut ENUM(\'OUVERTE\', \'COMPLETE\', \'ANNULEE\') DEFAULT \'OUVERTE\', CHANGE user_id user_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_40902137a76ed395 ON formations');
        $this->addSql('CREATE INDEX fk_userIdFormation ON formations (user_id)');
        $this->addSql('ALTER TABLE formations ADD CONSTRAINT FK_40902137A76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE messenger_messages CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE queue_name queue_name VARCHAR(190) NOT NULL');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE negociation DROP FOREIGN KEY FK_B5E137D8CE062FF9');
        $this->addSql('ALTER TABLE negociation DROP FOREIGN KEY FK_B5E137D89AE528DA');
        $this->addSql('ALTER TABLE negociation DROP FOREIGN KEY FK_B5E137D8CE062FF9');
        $this->addSql('ALTER TABLE negociation DROP FOREIGN KEY FK_B5E137D89AE528DA');
        $this->addSql('ALTER TABLE negociation CHANGE montant montant DOUBLE PRECISION NOT NULL, CHANGE taux_propose taux_propose DOUBLE PRECISION NOT NULL, CHANGE status status ENUM(\'PROPOSED\', \'ACCEPTED\', \'REJECTED\') DEFAULT \'PROPOSED\' NOT NULL, CHANGE credit_id credit_id INT NOT NULL, CHANGE investor_id investor_id INT NOT NULL');
        $this->addSql('ALTER TABLE negociation ADD CONSTRAINT `fk_negociation_credit` FOREIGN KEY (credit_id) REFERENCES credit (id_credit) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE negociation ADD CONSTRAINT `fk_negociation_investor` FOREIGN KEY (investor_id) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_b5e137d8ce062ff9 ON negociation');
        $this->addSql('CREATE INDEX fk_negociation_credit ON negociation (credit_id)');
        $this->addSql('DROP INDEX idx_b5e137d89ae528da ON negociation');
        $this->addSql('CREATE INDEX fk_negociation_investor ON negociation (investor_id)');
        $this->addSql('ALTER TABLE negociation ADD CONSTRAINT FK_B5E137D8CE062FF9 FOREIGN KEY (credit_id) REFERENCES credit (id_credit)');
        $this->addSql('ALTER TABLE negociation ADD CONSTRAINT FK_B5E137D89AE528DA FOREIGN KEY (investor_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE notification CHANGE type_notification type_notification ENUM(\'UPDATE_DETECTED\', \'DELETE_DETECTED\', \'BLOCKCHAIN_CORRUPTED\', \'DATA_RESTORED\') NOT NULL, CHANGE message message TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE is_read is_read TINYINT DEFAULT 0');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEEA76ED395');
        $this->addSql('ALTER TABLE orders CHANGE order_date order_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE shipping_address shipping_address TEXT NOT NULL, CHANGE user_id user_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_e52ffdeea76ed395 ON orders');
        $this->addSql('CREATE INDEX fk_userIdInOrders ON orders (user_id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEA76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY FK_52EA1F094584665A');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY FK_52EA1F098D9F6D38');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY FK_52EA1F094584665A');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY FK_52EA1F098D9F6D38');
        $this->addSql('ALTER TABLE order_item CHANGE product_id product_id INT NOT NULL, CHANGE order_id order_id INT NOT NULL');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT `fk_order_item_order` FOREIGN KEY (order_id) REFERENCES orders (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT `fk_order_item_product` FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_52ea1f098d9f6d38 ON order_item');
        $this->addSql('CREATE INDEX fk_order_item_order ON order_item (order_id)');
        $this->addSql('DROP INDEX idx_52ea1f094584665a ON order_item');
        $this->addSql('CREATE INDEX fk_order_item_product ON order_item (product_id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F094584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F098D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE participations DROP FOREIGN KEY FK_FDC6C6E8BCAA0AE9');
        $this->addSql('ALTER TABLE participations DROP FOREIGN KEY FK_FDC6C6E8BCAA0AE9');
        $this->addSql('ALTER TABLE participations DROP FOREIGN KEY FK_FDC6C6E85D419CCB');
        $this->addSql('ALTER TABLE participations CHANGE dateInscription dateInscription DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE statut statut ENUM(\'PAYEE\', \'ANNULEE\') DEFAULT \'PAYEE\', CHANGE presence presence TINYINT DEFAULT 0, CHANGE note note FLOAT DEFAULT NULL, CHANGE idFormation idFormation INT NOT NULL, CHANGE idUtilisateur idUtilisateur INT NOT NULL');
        $this->addSql('DROP INDEX idx_fdc6c6e8bcaa0ae9 ON participations');
        $this->addSql('CREATE INDEX fk_participation_formation ON participations (idFormation)');
        $this->addSql('DROP INDEX idx_fdc6c6e85d419ccb ON participations');
        $this->addSql('CREATE INDEX fk_userIdP ON participations (idUtilisateur)');
        $this->addSql('ALTER TABLE participations ADD CONSTRAINT FK_FDC6C6E8BCAA0AE9 FOREIGN KEY (idFormation) REFERENCES formations (idFormation)');
        $this->addSql('ALTER TABLE participations ADD CONSTRAINT FK_FDC6C6E85D419CCB FOREIGN KEY (idUtilisateur) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADA76ED395');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADA76ED395');
        $this->addSql('ALTER TABLE product CHANGE description description TEXT DEFAULT NULL, CHANGE price price DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE discount_price discount_price DOUBLE PRECISION DEFAULT \'0\', CHANGE brand brand VARCHAR(100) DEFAULT NULL, CHANGE avg_rating avg_rating DOUBLE PRECISION DEFAULT \'0\', CHANGE image_url image_url TEXT DEFAULT NULL, CHANGE stock stock INT DEFAULT 0, CHANGE category category VARCHAR(50) DEFAULT NULL, CHANGE status status VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT `fk_product_user` FOREIGN KEY (user_id) REFERENCES utilisateur (id_user) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_d34a04ada76ed395 ON product');
        $this->addSql('CREATE INDEX fk_product_user ON product (user_id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADA76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_50159CA97E3C61F9');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_50159CA97E3C61F9');
        $this->addSql('ALTER TABLE projet CHANGE description description TEXT DEFAULT NULL, CHANGE status status ENUM(\'DRAFT\', \'ACTIVE\', \'CLOSED\') DEFAULT \'DRAFT\' NOT NULL, CHANGE image_url image_url TEXT DEFAULT NULL, CHANGE secteur secteur VARCHAR(50) DEFAULT \'Autre\', CHANGE owner_id owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT `fk_project_owner` FOREIGN KEY (owner_id) REFERENCES utilisateur (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_50159ca97e3c61f9 ON projet');
        $this->addSql('CREATE INDEX fk_project_owner ON projet (owner_id)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA97E3C61F9 FOREIGN KEY (owner_id) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE trade CHANGE trade_type trade_type ENUM(\'BUY\', \'SELL\') NOT NULL, CHANGE order_mode order_mode ENUM(\'MARKET\', \'LIMIT\') NOT NULL, CHANGE status status ENUM(\'PENDING\', \'ACTIVE\', \'COMPLETED\') NOT NULL');
        $this->addSql('CREATE INDEX fk_trade_user ON trade (user_id)');
        $this->addSql('CREATE INDEX fk_assetID ON trade (asset_id)');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D151023152');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1C80970A6');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D19D3484D1');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1398D64AA');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1181BA793');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D151023152');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1C80970A6');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D19D3484D1');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1398D64AA');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1181BA793');
        $this->addSql('ALTER TABLE transaction CHANGE type type ENUM(\'TRANSFERT\', \'RECHARGE\', \'RETRAIT\', \'ACHAT\', \'VENTE\', \'CONVERSION\') NOT NULL, CHANGE statut statut ENUM(\'Pending\', \'Processing\', \'Cancelled\', \'Failed\', \'Completed\') DEFAULT NULL, CHANGE date_transaction date_transaction DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE id_wallet_destination id_wallet_destination INT NOT NULL, CHANGE id_currency id_currency INT NOT NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_card` FOREIGN KEY (id_card) REFERENCES credit_card (id_card) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_currency` FOREIGN KEY (id_currency) REFERENCES currency (id_currency) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_transaction_conversion` FOREIGN KEY (id_conversion) REFERENCES conversion (id_conversion) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_wallet_destination` FOREIGN KEY (id_wallet_destination) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_wallet_source` FOREIGN KEY (id_wallet_source) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_723705d1398d64aa ON transaction');
        $this->addSql('CREATE INDEX fk_currency ON transaction (id_currency)');
        $this->addSql('DROP INDEX idx_723705d19d3484d1 ON transaction');
        $this->addSql('CREATE INDEX fk_card ON transaction (id_card)');
        $this->addSql('DROP INDEX idx_723705d151023152 ON transaction');
        $this->addSql('CREATE INDEX fk_wallet_source ON transaction (id_wallet_source)');
        $this->addSql('DROP INDEX idx_723705d1181ba793 ON transaction');
        $this->addSql('CREATE INDEX fk_transaction_conversion ON transaction (id_conversion)');
        $this->addSql('DROP INDEX idx_723705d1c80970a6 ON transaction');
        $this->addSql('CREATE INDEX fk_wallet_destination ON transaction (id_wallet_destination)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D151023152 FOREIGN KEY (id_wallet_source) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1C80970A6 FOREIGN KEY (id_wallet_destination) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D19D3484D1 FOREIGN KEY (id_card) REFERENCES credit_card (id_card)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1398D64AA FOREIGN KEY (id_currency) REFERENCES currency (id_currency)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1181BA793 FOREIGN KEY (id_conversion) REFERENCES conversion (id_conversion)');
        $this->addSql('ALTER TABLE utilisateur CHANGE role role ENUM(\'ADMIN\', \'INVESTISSEUR\', \'COMMERCANT\', \'CLIENT\') NOT NULL, CHANGE date_de_creation date_de_creation DATETIME DEFAULT \'current_timestamp(6)\' NOT NULL, CHANGE date_derniere_connexion date_derniere_connexion DATETIME DEFAULT \'current_timestamp(6)\' NOT NULL, CHANGE statut statut ENUM(\'ACTIVE\', \'PENDING\', \'DESACTIVE\', \'\') NOT NULL');
        $this->addSql('ALTER TABLE wallet DROP FOREIGN KEY FK_7C68921F6B3CA4B');
        $this->addSql('ALTER TABLE wallet CHANGE rib rib VARCHAR(8) NOT NULL, CHANGE type_wallet type_wallet ENUM(\'fiat\', \'crypto\', \'trading\') DEFAULT NULL, CHANGE statut statut ENUM(\'bloque\', \'actif\') DEFAULT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE date_derniere_modification date_derniere_modification DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE id_user id_user INT NOT NULL');
        $this->addSql('DROP INDEX idx_7c68921f6b3ca4b ON wallet');
        $this->addSql('CREATE INDEX id_user ON wallet (id_user)');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921F6B3CA4B FOREIGN KEY (id_user) REFERENCES utilisateur (id_user)');
        $this->addSql('ALTER TABLE wallet_currency DROP FOREIGN KEY FK_9DF33C4B5A5F27F2');
        $this->addSql('ALTER TABLE wallet_currency DROP FOREIGN KEY FK_9DF33C4B398D64AA');
        $this->addSql('ALTER TABLE wallet_currency DROP FOREIGN KEY FK_9DF33C4B5A5F27F2');
        $this->addSql('ALTER TABLE wallet_currency DROP FOREIGN KEY FK_9DF33C4B398D64AA');
        $this->addSql('ALTER TABLE wallet_currency CHANGE solde solde DOUBLE PRECISION DEFAULT \'0.00\', CHANGE nom_currency nom_currency VARCHAR(11) NOT NULL, CHANGE id_wallet id_wallet INT NOT NULL, CHANGE id_currency id_currency INT NOT NULL');
        $this->addSql('ALTER TABLE wallet_currency ADD CONSTRAINT `fk_wallet` FOREIGN KEY (id_wallet) REFERENCES wallet (id_wallet) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wallet_currency ADD CONSTRAINT `fk_wc_currency` FOREIGN KEY (id_currency) REFERENCES currency (id_currency) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_9df33c4b398d64aa ON wallet_currency');
        $this->addSql('CREATE INDEX fk_wc_currency ON wallet_currency (id_currency)');
        $this->addSql('DROP INDEX idx_9df33c4b5a5f27f2 ON wallet_currency');
        $this->addSql('CREATE INDEX fk_wallet ON wallet_currency (id_wallet)');
        $this->addSql('ALTER TABLE wallet_currency ADD CONSTRAINT FK_9DF33C4B5A5F27F2 FOREIGN KEY (id_wallet) REFERENCES wallet (id_wallet)');
        $this->addSql('ALTER TABLE wallet_currency ADD CONSTRAINT FK_9DF33C4B398D64AA FOREIGN KEY (id_currency) REFERENCES currency (id_currency)');
    }
}
