# config/services.yaml
parameters:
    products_images_directory: '%kernel.project_dir%/public/uploads/products'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'

    App\Controller\BackOffice\:
        resource: '../src/Controller/backOffice/'
        tags: ['controller.service_arguments']