parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'

    App\Service\SmsVerificationService:
        arguments:
            $twilioSid:       '%env(TWILIO_SID)%'
            $twilioToken:     '%env(TWILIO_TOKEN)%'
            $twilioVerifySid: '%env(TWILIO_VERIFY_SID)%'